[package]
name = "ext_url"
description = "Module loader for deno_url"
edition.workspace = true
license.workspace = true
version.workspace = true
repository.workspace = true

[lib]
path = "lib.rs"

[dependencies]
deno_url = "0.122.0"
deno_core = { workspace = true }